name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push ${{ matrix.image }}
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.image }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: yuzulator/azure-pipelines-docker-agent:${{ matrix.image }}
